# Generated by Django 3.0.7 on 2020-06-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='description_long',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description_short',
        ),
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.CharField(default='placeId', max_length=100, unique=True),
        ),
    ]
