# Generated by Django 3.0.7 on 2020-07-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20200630_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description_long',
            field=models.TextField(default='Подробное описание'),
        ),
        migrations.AddField(
            model_name='location',
            name='description_short',
            field=models.TextField(default='Описание'),
        ),
    ]
