# Generated by Django 3.0.7 on 2020-07-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_location_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='place_id',
            field=models.CharField(default='placeId', max_length=100),
        ),
    ]
