# Generated by Django 3.0.7 on 2020-07-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20200714_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='place_id',
            field=models.CharField(default='placeId', max_length=100, unique=True),
        ),
    ]
