# Generated by Django 3.0.7 on 2020-07-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20200727_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.RemoveField(
            model_name='location',
            name='position',
        ),
    ]
