# Generated by Django 3.0.7 on 2020-07-27 12:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20200727_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description_long',
            field=tinymce.models.HTMLField(default='Подробное описание'),
        ),
    ]
