# Generated by Django 3.0.7 on 2020-08-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20200727_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='place_id',
        ),
    ]
